# Generated by Django 4.2.13 on 2024-05-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='evaluationcriterion',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': [('can_change_teacher', 'Can change teacher'), ('can_change_curriculum', 'Can change Curriculum')], 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AddField(
            model_name='curriculum',
            name='end_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='start_year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AddField(
            model_name='teacher',
            name='HocVi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('curriculums', models.ManyToManyField(to='courses.curriculum')),
            ],
        ),
    ]
